// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyusxqvtarxfigfifhzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dXN4cXZ0YXJ4ZmlnZmlmaHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjQxNTYsImV4cCI6MjA3MDE0MDE1Nn0.wspeN2sYgkuLV_gJW_9TZw3XV0wOnCNurX7Df9P6YlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});